### ISSUE TITLE
Symfony 2.3 (LTS) support

### ISSUE THREAD

**Issue by leggiero** [evheniy/JqueryBundle#1]
This bundle is really useful, but requires Symfony >= 2.4, would be useful to support Symfony 2.3 (LTS) version.

**Comment by evheniy** [comment]
Hi
Thank you for your comment.
I changed requires to Symfony 2.3.
Could you please test new tag 1.4.1?

**Comment by evheniy** [comment]
I tested it on Symfony2.3 and it works so I can close this issue
