### ISSUE TITLE
Symfony 3: getGlobals() method  without explicitly implementing Twig_Extension_GlobalsInterface is deprecated

### ISSUE THREAD

**Issue by godzillante** [evheniy/JqueryBundle#2]
Hi,

I get this Deprecation warning in Symfony 3:

Defining the getGlobals() method in the "twitter_bootstrap" extension without explicitly implementing Twig_Extension_GlobalsInterface is deprecated since version 1.23.

The issue can be solved by implementing `Twig_Extension_GlobalsInterface` in `vendor/evheniy/jquery-bundle/Evheniy/JqueryBundle/Twig/JqueryExtension.php` (row 12). This is also true for twitter-bootstrap-bundle.

I can submit a pull request if you like.

**Comment by evheniy** [comment]
Hi. It would be great. Thank you

**Comment by evheniy** [comment]
Done
